--------------------------------------------------------
--  Constraints for Table CUST_DETAILS
--------------------------------------------------------

  ALTER TABLE "BATMAN12"."CUST_DETAILS" ADD CONSTRAINT "CUST_DETAILS_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN12"."CUST_DETAILS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BATMAN12"."CUST_DETAILS" MODIFY ("CUST_ID" NOT NULL ENABLE);
