--------------------------------------------------------
--  Constraints for Table ROOM_DETAILS
--------------------------------------------------------

  ALTER TABLE "BATMAN12"."ROOM_DETAILS" ADD CONSTRAINT "ROOM_DETAILS_PK" PRIMARY KEY ("ROOM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BATMAN12"."ROOM_DETAILS" MODIFY ("ROOM_NO" NOT NULL ENABLE);
