--------------------------------------------------------
--  DDL for Table BILL_PAYMENT
--------------------------------------------------------

  CREATE TABLE "BATMAN12"."BILL_PAYMENT" 
   (	"BILL_NO" NUMBER, 
	"SUBTOTAL" NUMBER, 
	"TOTAL" NUMBER, 
	"DISCOUNT" VARCHAR2(20 BYTE), 
	"TAX" VARCHAR2(20 BYTE), 
	"BILL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
