--------------------------------------------------------
--  DDL for Table EXTRA_CHARGES
--------------------------------------------------------

  CREATE TABLE "BATMAN12"."EXTRA_CHARGES" 
   (	"ID_EXTRA_CHARGES" NUMBER, 
	"RESTAURANT_CHARGES" NUMBER, 
	"GAME_CHARGES" NUMBER, 
	"LAUNDARY_CHARGES" NUMBER, 
	"SERVICE_CHARGES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
