--------------------------------------------------------
--  Ref Constraints for Table BILL_PAYMENT
--------------------------------------------------------

  ALTER TABLE "BATMAN12"."BILL_PAYMENT" ADD CONSTRAINT "BILL_DUR_FOREIGN" FOREIGN KEY ("BILL_NO")
	  REFERENCES "BATMAN12"."DURATION" ("DURATION_ID") ENABLE;
  ALTER TABLE "BATMAN12"."BILL_PAYMENT" ADD CONSTRAINT "BILL_EXTRA_FOREIGN" FOREIGN KEY ("BILL_NO")
	  REFERENCES "BATMAN12"."EXTRA_CHARGES" ("ID_EXTRA_CHARGES") ENABLE;
