--------------------------------------------------------
--  Ref Constraints for Table DURATION
--------------------------------------------------------

  ALTER TABLE "BATMAN12"."DURATION" ADD CONSTRAINT "DUR_BILL_FOREIGN" FOREIGN KEY ("DURATION_ID")
	  REFERENCES "BATMAN12"."BILL_PAYMENT" ("BILL_NO") ENABLE;
  ALTER TABLE "BATMAN12"."DURATION" ADD CONSTRAINT "DUR_CUST_FOREIGN" FOREIGN KEY ("DURATION_ID")
	  REFERENCES "BATMAN12"."CUST_DETAILS" ("CUST_ID") ENABLE;
  ALTER TABLE "BATMAN12"."DURATION" ADD CONSTRAINT "DUR_EXTRA_FOREIGN" FOREIGN KEY ("DURATION_ID")
	  REFERENCES "BATMAN12"."EXTRA_CHARGES" ("ID_EXTRA_CHARGES") ENABLE;
  ALTER TABLE "BATMAN12"."DURATION" ADD CONSTRAINT "DUR_ROOM_FOREIGN" FOREIGN KEY ("DURATION_ID")
	  REFERENCES "BATMAN12"."ROOM_DETAILS" ("ROOM_NO") ENABLE;
