--------------------------------------------------------
--  Ref Constraints for Table EXTRA_CHARGES
--------------------------------------------------------

  ALTER TABLE "BATMAN12"."EXTRA_CHARGES" ADD CONSTRAINT "EXTRA_BILL_FOREIGN" FOREIGN KEY ("ID_EXTRA_CHARGES")
	  REFERENCES "BATMAN12"."BILL_PAYMENT" ("BILL_NO") ENABLE;
  ALTER TABLE "BATMAN12"."EXTRA_CHARGES" ADD CONSTRAINT "EXTRA_DUR_FOREIGN" FOREIGN KEY ("ID_EXTRA_CHARGES")
	  REFERENCES "BATMAN12"."DURATION" ("DURATION_ID") ENABLE;
